### ISSUE TITLE
No support for @CurrentIteration

### ISSUE THREAD

**Issue by Winkiel** [arsenikstiger/querytile-extended#1]
Hi,

When I use Iteration `Path = @CurrentIteration` in Query filter I get an error in extension:
```
Widget error

TF400496: Your team has not configured its schedule and iterations.
```

**Comment by NightOwlCoder** [comment]
Same here:

The specified team, 'Products\Delivery Team', hasn't scheduled an iteration for '@CurrentIteration'. Either <a href="https://go.microsoft.com/fwlink/?linkid=865408">change the team selection</a> or <a href="/Products/Delivery%20Team/_admin/_work?_a=iterations">configure iterations for the team</a>.

**Comment by arsenikstiger** [comment]
In fact this feature, aka @CurrentIteration, is a special iteration the scrum master must set in the configuration of TFS.
Ask him to configure it or you won't be able to use it.

**Comment by Winkiel** [comment]
I am the Scrum Master. @CurrentIteration is configured. It only doesn't work with this extension.

**Comment by arsenikstiger** [comment]
That's interesting.
I've developped it and installed it for my developpers, and obviously I'm using @CurrentIteration.

Would you have more information about this bug ?
Are you using it on TFS or VSTS/Azure DevOps ?
Which language is configured ?

-------- Message d'origine --------
De : Bartłomiej Narożnik <notifications@github.com>
Date : 09/01/2019 20:45 (GMT+01:00)
À : arsenikstiger/querytile-extended <querytile-extended@noreply.github.com>
Cc : arsenikstiger <arsenikstiger92@hotmail.com>, State change <state_change@noreply.github.com>
Objet : Re: [arsenikstiger/querytile-extended] No support for @CurrentIteration (#1)


I am the Scrum Master. @CurrentIteration is configured. It only doesn't work with this extension.

**Comment by Winkiel** [comment]
I've looked into it and maybe the problem is that I have Iteration per Teams. So @CurrentIteration is only on a Team level. And when I click on the widget that opens a Query in a Project context (loses the team).
But query would work fine when I'm in a context of a Team. I have also standard Query Tile widgets on the same Dashboard and they work fine. When I click on them they open query in Team conext.
I am using TFS.
