### ISSUE TITLE
Reference to non-existing javacsript file

### ISSUE THREAD

**Issue by PeterKristiansen** [arsenikstiger/querytile-extended#3]
Hi,

We've found what appears to be a minor issue that a referenced file - array-polyfill.js - cannot be found.

`Failed to load ressource: the server responded with a status of 404 (Not found) array-polyfill.js:1`

And
`widget.html:1 Refused to execute script from 'http://tfs:8080/tfs/_apis/public/gallery/publisher/aurelien-sudre/extension/querytile-extended/1.0.0/assetbyname/scripts/array-polyfill.js' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.`
Which could make sense given that the file cannot be found.

We've found that you include the script in configuration.html and widget.html.

We are currently running TFS 2017 update 2.

Best regards
Peter

**Comment by arsenikstiger** [comment]
Fixed

**Comment by ravensorb** [comment]
I am still running into this issue -- have you published an update?
