### ISSUE TITLE
Sum operation fails if values are missing

### ISSUE THREAD

**Issue by gbates1989** [arsenikstiger/querytile-extended#4]
I've configured a query tile extended to sum all of the effort values returned from a query. 

The objective is to have the tile display the total amount of effort under a query so the team can see it tick down each day. The tile is returning a widget error of "Unable to get property 'length' of undefined or null reference".

I wonder if this is because some of the items in the query have not yet been estimated. If so, could the widget assume an empty value to be 0?

**Comment by arsenikstiger** [comment]
Sorry for the very late response, but I have the same need, display a sum from different values (null values included) and it does work.
