### ISSUE TITLE
Widget failed to load

### ISSUE THREAD

**Issue by eduardo-reus-souza** [arsenikstiger/querytile-extended#6]
Hi folks
I have a problem with Query Tile Extended. My dashboard was working normally. But today the cards have the message "Widget failed to load" and when I click on "more details" the message "Query Tile Extended has a problem."
I reinforce that the dashboard was working and we did not change the query it consumes.

**Comment by Rodriguez95** [comment]
> Hola amigos
> , tengo un problema con Query Tile Extended. Mi tablero funcionaba normalmente. Pero hoy las tarjetas tienen el mensaje "Error al cargar el widget" y cuando hago clic en "más detalles" aparece el mensaje "Query Tile Extended tiene un problema".
> Insisto en que el panel de control funcionaba y no cambiamos la consulta que consume.

Hola como estas, tengo exactamente el mismo problema con mi tablero...

**Comment by abeilard** [comment]
Hi guys
Have the same problem here, any fix?

**Comment by Motobahta** [comment]
I also have the same problem.  Error: Cannot read property 'length' of undefined.  It works for a flat query, but not when I use a query that shows children.
