### ISSUE TITLE
Problem when there are more than 200 items

### ISSUE THREAD

**Issue by tiagosantoss** [arsenikstiger/querytile-extended#7]
Hi,

This extension has been useful but has a problem when there are more than 200 items.

I believe the problem is due to the 200 limitation of the service described in this link [https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20items/get%20work%20items%20batch?view=azure-devops-rest-5.1](https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20items/get%20work%20items%20batch?view=azure-devops-rest-5.1)

It would be interesting to resolve this issue by making more than one call, so you could retrieve all the necessary items.

**Comment by kevindw-realdolmen** [comment]
Hi,

I am also running into this problem, could this be updated?

**Comment by pa1-gulati** [comment]
Running into the same issue when there are more than 200 items. Any workaround or fix?

**Comment by Lariel** [comment]
Hi!
There's some update about this?
I saw [this pull request](https://github.com/arsenikstiger/querytile-extended/pull/8) but its has in conflicts.

**Comment by romulogomesti** [comment]
Hey guys. Having the same issue here. How can we contact @arsenikstiger ?

**Comment by arsenikstiger** [comment]
Hello everyone!
Better late than never.
I just deployed an update, 5 years later...
Please let me know if it resolves this issue.
Thank you.
